### ISSUE TITLE
issue of this:

### ISSUE THREAD

**Issue by JDJGInc** [Helow19274/aiogTTS#1]
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 902, in invoke
    await ctx.command.invoke(ctx)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/core.py", line 864, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ValueError: Unable to find token seed! Did https://translate.google.com change?

**Comment by JDJGInc** [comment]
please fix this.

**Comment by Helow19274** [comment]
@JDJGInc I'm sorry for the late reply. Check it out again, everything should work okay :)
